v1.0.4 (2018-04-15)
- Fixed website url in addon.xml (thanks Dangelus!)
- removing non-ascii characters in title in parameters to prevent
UnicodeDecodeError: 'ascii' codec can't decode ...
The error occured when doing urllib.parse.parse_qs of the parameters
- changed used url due to some urls not getting updated with the new
shows
- removed pineapple-university
- removed hak5 seasons